cadastro/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'cadastro'
urlpatterns = [
    # Empresa
    # cadastro/empresa/adicionar/
    path('empresa/adicionar/',
        views.AdicionarEmpresaView.as_view(), name='addempresaview'),
    # cadastro/empresa/listaempresas
    path('empresa/listaempresas/',
        views.EmpresasListView.as_view(), name='listaempresasview'),
    # cadastro/empresa/editar/
    path('empresa/editar/(?P<pk>[0-9]+)/',
        views.EditarEmpresaView.as_view(), name='editarempresaview'),

    # Cliente
    # cadastro/cliente/adicionar/
    path('cliente/adicionar/',
        views.AdicionarClienteView.as_view(), name='addclienteview'),
    # cadastro/cliente/listaclientes
    path('cliente/listaclientes/',
        views.ClientesListView.as_view(), name='listaclientesview'),
    # cadastro/cliente/editar/
    path('cliente/editar/(?P<pk>[0-9]+)/',
        views.EditarClienteView.as_view(), name='editarclienteview'),

    # Fornecedor
    # cadastro/fornecedor/adicionar/
    path('fornecedor/adicionar/',
        views.AdicionarFornecedorView.as_view(), name='addfornecedorview'),
    # cadastro/fornecedor/listafornecedores
    path('fornecedor/listafornecedores/',
        views.FornecedoresListView.as_view(), name='listafornecedoresview'),
    # cadastro/fornecedor/editar/
    path('fornecedor/editar/(?P<pk>[0-9]+)/',
        views.EditarFornecedorView.as_view(), name='editarfornecedorview'),

    # Transportadora
    # cadastro/transportadora/adicionar/
    path(r'transportadora/adicionar/$',
        views.AdicionarTransportadoraView.as_view(), name='addtransportadoraview'),
    # cadastro/transportadora/listatransportadoras
    path(r'transportadora/listatransportadoras/$',
        views.TransportadorasListView.as_view(), name='listatransportadorasview'),
    # cadastro/transportadora/editar/
    path(r'transportadora/editar/(?P<pk>[0-9]+)/$',
        views.EditarTransportadoraView.as_view(), name='editartransportadoraview'),

    # Produto
    # cadastro/produto/adicionar/
    path(r'produto/adicionar/$',
        views.AdicionarProdutoView.as_view(), name='addprodutoview'),
    # cadastro/produto/listaprodutos
    path(r'produto/listaprodutos/$',
        views.ProdutosListView.as_view(), name='listaprodutosview'),
    # cadastro/produto/listaprodutos/baixoestoque
    path(r'produto/listaprodutos/baixoestoque/$',
        views.ProdutosBaixoEstoqueListView.as_view(), name='listaprodutosbaixoestoqueview'),
    # cadastro/produto/editar/
    path(r'produto/editar/(?P<pk>[0-9]+)/$',
        views.EditarProdutoView.as_view(), name='editarprodutoview'),

    # Outros
    # Categorias
    # cadastro/outros/adicionarcategoria/
    path(r'outros/adicionarcategoria/$',
        views.AdicionarCategoriaView.as_view(), name='addcategoriaview'),
    # cadastro/outros/listacategorias/
    path(r'outros/listacategorias/$',
        views.CategoriasListView.as_view(), name='listacategoriasview'),
    # cadastro/outros/editarcategoria/
    path(r'outros/editarcategoria/(?P<pk>[0-9]+)/$',
        views.EditarCategoriaView.as_view(), name='editarcategoriaview'),

    # Unidades
    # cadastro/outros/adicionarunidade/
    path(r'outros/adicionarunidade/$',
        views.AdicionarUnidadeView.as_view(), name='addunidadeview'),
    # cadastro/outros/listaunidades/
    path(r'outros/listaunidades/$',
        views.UnidadesListView.as_view(), name='listaunidadesview'),
    # cadastro/outros/editarcunidade/
    path(r'outros/editarunidade/(?P<pk>[0-9]+)/$',
        views.EditarUnidadeView.as_view(), name='editarunidadeview'),

    # Marcas
    # cadastro/outros/adicionarmarca/
    path(r'outros/adicionarmarca/$',
        views.AdicionarMarcaView.as_view(), name='addmarcaview'),
    # cadastro/outros/listamarcas/
    path(r'outros/listamarcas/$',
        views.MarcasListView.as_view(), name='listamarcasview'),
    # cadastro/outros/editarmarca/
    path(r'outros/editarmarca/(?P<pk>[0-9]+)/$',
        views.EditarMarcaView.as_view(), name='editarmarcaview'),

    # Informacoes de dada empresa (Ajax request)
    path(r'infoempresa/$', views.InfoEmpresa.as_view(), name='infoempresa'),
    path(r'infofornecedor/$', views.InfoFornecedor.as_view(), name='infofornecedor'),
    path(r'infocliente/$', views.InfoCliente.as_view(), name='infocliente'),
    path(r'infotransportadora/$', views.InfoTransportadora.as_view(),
        name='infotransportadora'),
    path(r'infoproduto/$', views.InfoProduto.as_view(), name='infoproduto'),
]

financeiro/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'financeiro'
urlpatterns = [
    # Lancamentos
    # Gerar lancamento
    path(r'gerarlancamento/$', views.GerarLancamentoView.as_view(),
        name='gerarlancamento'),
    # Lista todos lancamentos
    path(r'lancamentos/$', views.LancamentoListView.as_view(),
        name='listalancamentoview'),

    # Contas a pagar
    # financeiro/contapagar/adicionar/
    path(r'contapagar/adicionar/$',
        views.AdicionarContaPagarView.as_view(), name='addcontapagarview'),
    # financeiro/contapagar/listacontapagar
    path(r'contapagar/listacontapagar/$',
        views.ContaPagarListView.as_view(), name='listacontapagarview'),
    # financeiro/contapagar/editar/
    path(r'contapagar/editar/(?P<pk>[0-9]+)/$',
        views.EditarContaPagarView.as_view(), name='editarcontapagarview'),
    # financeiro/contapagar/listacontapagar/atrasadas/
    path(r'contapagar/listacontapagar/atrasadas/$',
        views.ContaPagarAtrasadasListView.as_view(), name='listacontapagaratrasadasview'),
    # financeiro/contapagar/listacontapagar/hoje/
    path(r'contapagar/listacontapagar/hoje/$',
        views.ContaPagarHojeListView.as_view(), name='listacontapagarhojeview'),

    # Contas a receber
    # financeiro/contareceber/adicionar/
    path(r'contareceber/adicionar/$',
        views.AdicionarContaReceberView.as_view(), name='addcontareceberview'),
    # financeiro/contareceber/listacontapagar
    path(r'contareceber/listacontareceber/$',
        views.ContaReceberListView.as_view(), name='listacontareceberview'),
    # financeiro/contareceber/editar/
    path(r'contareceber/editar/(?P<pk>[0-9]+)/$',
        views.EditarContaReceberView.as_view(), name='editarcontareceberview'),
    # financeiro/contareceber/listacontapagar/atrasadas/
    path(r'contareceber/listacontareceber/atrasadas/$',
        views.ContaReceberAtrasadasListView.as_view(), name='listacontareceberatrasadasview'),
    # financeiro/contareceber/listacontapagar/hoje/
    path(r'contareceber/listacontareceber/hoje/$',
        views.ContaReceberHojeListView.as_view(), name='listacontareceberhojeview'),

    # Pagamentos
    # financeiro/pagamento/adicionar/
    path(r'pagamento/adicionar/$',
        views.AdicionarSaidaView.as_view(), name='addpagamentoview'),
    # financeiro/pagamento/listacontapagar
    path(r'pagamento/listapagamento/$',
        views.SaidaListView.as_view(), name='listapagamentosview'),
    # financeiro/pagamento/editar/
    path(r'pagamento/editar/(?P<pk>[0-9]+)/$',
        views.EditarSaidaView.as_view(), name='editarpagamentoview'),

    # Recebimentos
    # financeiro/recebimento/adicionar/
    path(r'recebimento/adicionar/$',
        views.AdicionarEntradaView.as_view(), name='addrecebimentoview'),
    # financeiro/recebimento/listarecebimento
    path(r'recebimento/listarecebimento/$',
        views.EntradaListView.as_view(), name='listarecebimentosview'),
    # financeiro/recebimento/editar/
    path(r'recebimento/editar/(?P<pk>[0-9]+)/$',
        views.EditarEntradaView.as_view(), name='editarrecebimentoview'),

    # Faturar Pedido de venda
    path(r'faturarpedidovenda/(?P<pk>[0-9]+)/$',
        views.FaturarPedidoVendaView.as_view(), name='faturarpedidovenda'),
    # Faturar Pedido de compra
    path(r'faturarpedidocompra/(?P<pk>[0-9]+)/$',
        views.FaturarPedidoCompraView.as_view(), name='faturarpedidocompra'),

    # Plano de contas
    # financeiro/planodecontas
    path(r'planodecontas/$', views.PlanoContasView.as_view(), name='planocontasview'),
    # financeiro/planodecontas/adicionargrupo/
    path(r'planodecontas/adicionargrupo/$',
        views.AdicionarGrupoPlanoContasView.as_view(), name='addgrupoview'),
    # financeiro/planodecontas/editargrupo/
    path(r'planodecontas/editargrupo/(?P<pk>[0-9]+)/$',
        views.EditarGrupoPlanoContasView.as_view(), name='editargrupoview'),

    # Fluxo de caixa
    # financeiro/fluxodecaixa
    path(r'fluxodecaixa/$', views.FluxoCaixaView.as_view(), name='fluxodecaixaview'),
]

tcc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('cadastro/', include('cadastro.urls')),
    path('fiscal/', include('fiscal.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
    path('financeiro/', include('financeiro.urls')),
    path('estoque/', include('estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

financeiro/models/lancamento.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.urls import reverse_lazy
from django.template.defaultfilters import date

import locale
locale.setlocale(locale.LC_ALL, '')

STATUS_CONTA_SAIDA_ESCOLHAS = (
    (u'0', u'Paga'),
    (u'1', u'A pagar'),
    (u'2', u'Atrasada'),
)

STATUS_CONTA_ENTRADA_ESCOLHAS = (
    (u'0', u'Recebida'),
    (u'1', u'A receber'),
    (u'2', u'Atrasada'),
)


class Lancamento(models.Model):
    data_vencimento = models.DateField(null=True, blank=True)
    data_pagamento = models.DateField(null=True, blank=True)
    descricao = models.CharField(max_length=255)
    conta_corrente = models.ForeignKey(
        'cadastro.Banco', related_name="conta_corrente_conta", on_delete=models.SET_NULL, null=True, blank=True)
    valor_total = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                      MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    abatimento = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    juros = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    valor_liquido = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                        MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    movimentar_caixa = models.BooleanField(default=True)
    movimento_caixa = models.ForeignKey(
        'financeiro.MovimentoCaixa', related_name="movimento_caixa_lancamento", on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "Lançamento"

    def format_valor_liquido(self):
        return locale.format(u'%.2f', self.valor_liquido, 1)

    @property
    def format_data_vencimento(self):
        return '%s' % date(self.data_vencimento, "d/m/Y")

    @property
    def format_data_pagamento(self):
        return '%s' % date(self.data_pagamento, "d/m/Y")


class Entrada(Lancamento):
    cliente = models.ForeignKey('cadastro.Cliente', related_name="conta_cliente",
                                on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(
        max_length=1, choices=STATUS_CONTA_ENTRADA_ESCOLHAS, default='1')
    grupo_plano = models.ForeignKey(
        'financeiro.PlanoContasGrupo', related_name="grupo_plano_recebimento", on_delete=models.SET_NULL, null=True, blank=True)

    def get_edit_url(self):
        if self.status == '0':
            return reverse_lazy('financeiro:editarrecebimentoview', kwargs={'pk': self.id})
        else:
            return reverse_lazy('financeiro:editarcontareceberview', kwargs={'pk': self.id})

    def get_tipo(self):
        return 'Entrada'


class Saida(Lancamento):
    fornecedor = models.ForeignKey(
        'cadastro.Fornecedor', related_name="conta_fornecedor", on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(
        max_length=1, choices=STATUS_CONTA_SAIDA_ESCOLHAS, default='1')
    grupo_plano = models.ForeignKey(
        'financeiro.PlanoContasGrupo', related_name="grupo_plano_pagamento", on_delete=models.SET_NULL, null=True, blank=True)

    def get_edit_url(self):
        if self.status == '0':
            return reverse_lazy('financeiro:editarpagamentoview', kwargs={'pk': self.id})
        else:
            return reverse_lazy('financeiro:editarcontapagarview', kwargs={'pk': self.id})

    def get_tipo(self):
        return 'Saida'


class MovimentoCaixa(models.Model):
    data_movimento = models.DateField(null=True, blank=True)
    saldo_inicial = models.DecimalField(
        max_digits=13, decimal_places=2, default=Decimal('0.00'))
    saldo_final = models.DecimalField(
        max_digits=13, decimal_places=2, default=Decimal('0.00'))
    entradas = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    saidas = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))

    class Meta:
        verbose_name = "Movimento de Caixa"
        permissions = (
            ("acesso_fluxodecaixa", "Pode acessar o Fluxo de Caixa"),
        )

    @property
    def format_data_movimento(self):
        return '%s' % date(self.data_movimento, "d/m/Y")

    @property
    def valor_lucro_prejuizo(self):
        return self.saldo_final - self.saldo_inicial

    def __unicode__(self):
        s = u'Movimento dia %s' % (self.data_movimento)
        return s

    def __str__(self):
        s = u'Movimento dia %s' % (self.data_movimento)
        return s

financeiro/models/plano.py
# -*- coding: utf-8 -*-

from django.db import models

TIPO_GRUPO_ESCOLHAS = (
    (u'0', u'Entrada'),
    (u'1', u'Saída'),
)


class PlanoContasGrupo(models.Model):
    codigo = models.CharField(max_length=6)
    tipo_grupo = models.CharField(max_length=1, choices=TIPO_GRUPO_ESCOLHAS)
    descricao = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Grupo do Plano de Contas"

    def __unicode__(self):
        s = u'%s' % (self.descricao)
        return s

    def __str__(self):
        s = u'%s' % (self.descricao)
        return s


class PlanoContasSubgrupo(PlanoContasGrupo):
    grupo = models.ForeignKey('financeiro.PlanoContasGrupo',
                              related_name="subgrupos", on_delete=models.CASCADE)

financeiro/forms/plano.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _
from django.forms import inlineformset_factory

from financeiro.models import PlanoContasGrupo, PlanoContasSubgrupo


class PlanoContasGrupoForm(forms.ModelForm):

    class Meta:
        model = PlanoContasGrupo
        fields = ('tipo_grupo', 'descricao',)
        widgets = {
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_grupo': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'descricao': _('Descrição'),
            'tipo_grupo': _('Tipo de lançamento'),
        }


class PlanoContasSubgrupoForm(forms.ModelForm):

    class Meta:
        model = PlanoContasSubgrupo
        fields = ('descricao',)
        widgets = {
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'descricao': _('Descrição'),
        }


PlanoContasSubgrupoFormSet = inlineformset_factory(
    PlanoContasGrupo, PlanoContasSubgrupo, form=PlanoContasSubgrupoForm, fk_name='grupo', extra=1, can_delete=True)

financeiro/views/fluxo_de_caixa.py
# -*- coding: utf-8 -*-

from django.urls import reverse_lazy
from django.contrib import messages

from base.custom_views import CustomListView

from financeiro.models import MovimentoCaixa

from datetime import datetime


class FluxoCaixaView(CustomListView):
    template_name = "financeiro/fluxo_de_caixa/fluxo.html"
    success_url = reverse_lazy('financeiro:fluxodecaixaview')
    context_object_name = 'movimentos'
    permission_codename = 'acesso_fluxodecaixa'

    def get_queryset(self):
        try:
            data_inicial = self.request.GET.get('from')
            data_final = self.request.GET.get('to')

            if data_inicial and data_final:
                data_inicial = datetime.strptime(data_inicial, '%d/%m/%Y')
                data_final = datetime.strptime(data_final, '%d/%m/%Y')
            elif data_inicial:
                data_inicial = datetime.strptime(data_inicial, '%d/%m/%Y')
                data_final = data_inicial
            elif data_final:
                data_final = datetime.strptime(data_final, '%d/%m/%Y')
                data_inicial = data_final
            else:
                data_final = data_inicial = datetime.today().strftime('%Y-%m-%d')

        except ValueError:
            data_final = data_inicial = datetime.today().strftime('%Y-%m-%d')
            messages.error(
                self.request, 'Formato de data incorreto, deve ser no formato DD/MM/AAAA')

        return MovimentoCaixa.objects.filter(data_movimento__range=(data_inicial, data_final))

templates/financeiro/lancamento/lancamento_form.html
<!-- Body-->
<div class="body">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.descricao.label}}</label>{% if form.descricao.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.descricao.errors %}<label class="error">{% for error in form.descricao.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.descricao}}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.status.label}}</label>{% if form.status.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.status.errors %}<label class="error">{% for error in form.status.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.status}}
          <input type="hidden" id="id_status" name="status" value="{{form.status.initial}}" />
        </div>
      </div>
    </div>

    {% if form.fornecedor %}
    <div class="col-sm-6">
      <div class="form-group">
        <label>{{form.fornecedor.label}}</label>{% if form.fornecedor.field.required %}<strong style="color:red;"> *</strong>{% endif %}
        {% if form.fornecedor.errors %}<label class="error">{% for error in form.fornecedor.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="input-group" style="margin-bottom: 0px;">
          <div class="form-line">
            {{form.fornecedor}}
          </div>
          <a class="input-group-addon newwindow" style="color: green;" title="Adicionar fornecedor" href="{% url 'cadastro:addfornecedorview' %}"><i class="material-icons add-new-icon" title="Adicionar fornecedor">&#xE147;</i></a>
        </div>
      </div>
    </div>
    {% else %}
    <div class="col-sm-6">
      <div class="form-group">
        <label>{{form.cliente.label}}</label>{% if form.cliente.field.required %}<strong style="color:red;"> *</strong>{% endif %}
        {% if form.cliente.errors %}<label class="error">{% for error in form.cliente.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="input-group" style="margin-bottom: 0px;">
          <div class="form-line">
            {{form.cliente}}
          </div>
          <a class="input-group-addon newwindow" style="color: green;" title="Adicionar cliente" href="{% url 'cadastro:addclienteview' %}"><i class="material-icons add-new-icon" title="Adicionar cliente">&#xE147;</i></a>
        </div>
      </div>
    </div>
    {% endif %}

    <div class="col-sm-6">
      <div class="form-group">
        <label>{{form.grupo_plano.label}}</label>{% if form.grupo_plano.field.required %}<strong style="color:red;"> *</strong>{% endif %}
        {% if form.grupo_plano.errors %}<label class="error">{% for error in form.grupo_plano.errors %}{{error}}{% endfor %}</label>{% endif %}
        <div class="input-group" style="margin-bottom: 0px;">
          <div class="form-line">
            {{form.grupo_plano}}
          </div>
          <a class="input-group-addon newwindow" style="color: green;" title="Adicionar classificação de saída" href="{% url 'financeiro:addgrupoview' %}"><i class="material-icons add-new-icon" title="Adicionar classificação de entrada/saída">&#xE147;</i></a>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.conta_corrente.label}}</label>{% if form.conta_corrente.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.conta_corrente.errors %}<label class="error">{% for error in form.conta_corrente.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.conta_corrente}}
        </div>
      </div>
    </div>

    {% if form.status.initial == '0' %}
    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.data_pagamento.label}}</label>{% if form.data_pagamento.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.data_pagamento.errors %}<label class="error">{% for error in form.data_pagamento.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.data_pagamento}}
        </div>
      </div>
    </div>
    {% endif %}

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.data_vencimento.label}}</label>{% if form.data_vencimento.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.data_vencimento.errors %}<label class="error">{% for error in form.data_vencimento.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.data_vencimento}}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.valor_total.label}}</label>{% if form.valor_total.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.valor_total.errors %}<label class="error">{% for error in form.valor_total.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.valor_total}}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.abatimento.label}}</label>{% if form.abatimento.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.abatimento.errors %}<label class="error">{% for error in form.abatimento.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.abatimento}}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.juros.label}}</label>{% if form.juros.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.juros.errors %}<label class="error">{% for error in form.juros.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.juros}}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.valor_liquido.label}}</label>{% if form.valor_liquido.field.required %}<strong style="color:red;"> *</strong>{% endif %}
          {% if form.valor_liquido.errors %}<label class="error">{% for error in form.valor_liquido.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.valor_liquido}}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <div class="form-line">
          {{form.movimentar_caixa}}
          <label for="id_movimentar_caixa" style="font-weight: bold;" title="Selecionar para debitar/creditar no fluxo de caixa.">{{form.movimentar_caixa.label}}</label>
        </div>
      </div>
    </div>

  </div>
  
  <button class="btn btn-success foot-btn" type="submit"><i class="material-icons">&#xE148;</i><span> SALVAR</span></button>
</div>
<!--#Body-->

templates/financeiro/lancamento/lancamento_jsblock.html
{% load static %}
<!-- JQuery Mask Input Js -->
<script src="{% static 'js/jquery.mask.js' %}"></script>

{% include 'base/load_jqueryui.html' %}

{% include 'base/datepicker_js.html' %}

{% include 'base/tooltip_js.html' %}

 <script type="text/javascript">
 	var req_urls = {}
 	req_urls.gerar_lancamento_url = "{% url 'financeiro:gerarlancamento' %}"

    $.Admin.maskInput.maskLancamento();
    $.Admin.lancamentoForm.init(req_urls);
  </script>

templates/financeiro/lancamento/modal_selecionar_data.html
<!-- Modal selecionar data do pagamento -->
<div class="modal fade modal_selecionar_data">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">SELECIONE A DATA DO PAGAMENTO</h4>
        <small style="color:red;">Salve as modificações antes de confirmar</small>
      </div>
      <div class="modal-body">
        <div class="container-fluid">

          <!-- Campos -->
          <div class="row">

            <div class="col-sm-12">
              <div class="form-group">
                <div class="form-line">
                  <label>Data do pagamento</label>
                  <input type="text" class="form-control datepicker" id="id_data_pagamento"/>
                </div>
              </div>
            </div>

            <input type="hidden" name="tipo_conta" id="id_tipo_conta"/>

            <input type="hidden" name="conta_id" id="id_conta_id" value="{{object.id}}"/>

          </div>
          <!-- #Campos -->
          
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" id="baixar_conta_confirma">CONFIRMA</button>
      </div>
    </div>
  </div>
</div>
<!-- #Modal selecionar data do pagamento -->