compras/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'compras'
urlpatterns = [
    # Orcamentos de compra
    # compras/orcamentocompra/adicionar/
    path(r'orcamentocompra/adicionar/$',
        views.AdicionarOrcamentoCompraView.as_view(), name='addorcamentocompraview'),
    # compras/orcamentocompra/listaorcamentocompra
    path(r'orcamentocompra/listaorcamentocompra/$',
        views.OrcamentoCompraListView.as_view(), name='listaorcamentocompraview'),
    # compras/orcamentocompra/editar/
    path(r'orcamentocompra/editar/(?P<pk>[0-9]+)/$',
        views.EditarOrcamentoCompraView.as_view(), name='editarorcamentocompraview'),
    # compras/orcamentocompra/listaorcamentocompra/vencidos/
    path(r'orcamentocompra/listaorcamentocompra/vencidos/$',
        views.OrcamentoCompraVencidosListView.as_view(), name='listaorcamentocompravencidosview'),
    # compras/orcamentocompra/listaorcamentocompra/hoje/
    path(r'orcamentocompra/listaorcamentocompra/hoje/$',
        views.OrcamentoCompraVencimentoHojeListView.as_view(), name='listaorcamentocomprahojeview'),

    # Pedidos de compra
    # compras/pedidocompra/adicionar/
    path(r'pedidocompra/adicionar/$',
        views.AdicionarPedidoCompraView.as_view(), name='addpedidocompraview'),
    # compras/pedidocompra/listapedidocompra
    path(r'pedidocompra/listapedidocompra/$',
        views.PedidoCompraListView.as_view(), name='listapedidocompraview'),
    # compras/pedidocompra/editar/
    path(r'pedidocompra/editar/(?P<pk>[0-9]+)/$',
        views.EditarPedidoCompraView.as_view(), name='editarpedidocompraview'),
    # compras/pedidocompra/listapedidocompra/atrasados/
    path(r'pedidocompra/listapedidocompra/atrasados/$',
        views.PedidoCompraAtrasadosListView.as_view(), name='listapedidocompraatrasadosview'),
    # compras/pedidocompra/listapedidocompra/hoje/
    path(r'pedidocompra/listapedidocompra/hoje/$',
        views.PedidoCompraEntregaHojeListView.as_view(), name='listapedidocomprahojeview'),

    # Request ajax
    path(r'infocompra/$', views.InfoCompra.as_view(), name='infocompra'),

    # Gerar pdf orcamento
    path(r'gerarpdforcamentocompra/(?P<pk>[0-9]+)/$',
        views.GerarPDFOrcamentoCompra.as_view(), name='gerarpdforcamentocompra'),
    # Gerar pdf pedido
    path(r'gerarpdfpedidocompra/(?P<pk>[0-9]+)/$',
        views.GerarPDFPedidoCompra.as_view(), name='gerarpdfpedidocompra'),
    # Gerar pedido a partir de um orçamento
    path(r'gerarpedidocompra/(?P<pk>[0-9]+)/$',
        views.GerarPedidoCompraView.as_view(), name='gerarpedidocompra'),
    # Copiar orcamento cancelado ou realizado
    path(r'copiarorcamentocompra/(?P<pk>[0-9]+)/$',
        views.GerarCopiaOrcamentoCompraView.as_view(), name='copiarorcamentocompra'),
    # Copiar pedido cancelado ou realizado
    path(r'copiarpedidocompra/(?P<pk>[0-9]+)/$',
        views.GerarCopiaPedidoCompraView.as_view(), name='copiarpedidocompra'),
    # Cancelar Pedido de compra
    path(r'cancelarpedidocompra/(?P<pk>[0-9]+)/$',
        views.CancelarPedidoCompraView.as_view(), name='cancelarpedidocompra'),
    # Cancelar Orcamento de compra
    path(r'cancelarorcamentocompra/(?P<pk>[0-9]+)/$',
        views.CancelarOrcamentoCompraView.as_view(), name='cancelarorcamentocompra'),
    # Receber Pedido de compra
    path(r'receberpedidocompra/(?P<pk>[0-9]+)/$',
        views.ReceberPedidoCompraView.as_view(), name='receberpedidocompra'),
]

tcc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('cadastro/', include('cadastro.urls')),
    path('fiscal/', include('fiscal.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
    path('financeiro/', include('financeiro.urls')),
    path('estoque/', include('estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

compras/models/compras.py
# -*- coding: utf-8 -*-

from django.db import models
from django.template.defaultfilters import date
from django.core.validators import MinValueValidator
from django.urls import reverse_lazy

from decimal import Decimal

from vendas.models import TIPOS_DESCONTO_ESCOLHAS, MOD_FRETE_ESCOLHAS, STATUS_ORCAMENTO_ESCOLHAS
from estoque.models import DEFAULT_LOCAL_ID

import locale
locale.setlocale(locale.LC_ALL, '')

STATUS_PEDIDO_COMPRA_ESCOLHAS = (
    (u'0', u'Aberto'),
    (u'1', u'Realizado'),
    (u'2', u'Cancelado'),
    (u'3', u'Importado por XML'),
    (u'4', u'Recebido')
)


class ItensCompra(models.Model):
    produto = models.ForeignKey('cadastro.Produto', related_name="compra_produto",
                                on_delete=models.CASCADE, null=True, blank=True)
    compra_id = models.ForeignKey(
        'compras.Compra', related_name="itens_compra", on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    valor_unit = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    tipo_desconto = models.CharField(
        max_length=1, choices=TIPOS_DESCONTO_ESCOLHAS, null=True, blank=True)
    desconto = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    subtotal = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    inf_ad_prod = models.CharField(max_length=500, null=True, blank=True)

    vicms = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    vipi = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                               MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    p_icms = models.DecimalField(max_digits=5, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    p_ipi = models.DecimalField(max_digits=5, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], null=True, blank=True)

    # Opcoes
    icms_incluido_preco = models.BooleanField(default=False)
    ipi_incluido_preco = models.BooleanField(default=False)
    incluir_bc_icms = models.BooleanField(
        default=False)  # incluir IPI na BC do ICMS
    auto_calcular_impostos = models.BooleanField(default=True)

    @property
    def vprod(self):
        return round(self.quantidade * self.valor_unit, 2)

    def get_total_sem_desconto(self):
        if self.tipo_desconto == '0':
            return self.subtotal + self.desconto
        else:
            tot_sem_desc = (self.subtotal * 100) / (100 - self.desconto)
            return tot_sem_desc

    def get_valor_desconto(self):
        if self.tipo_desconto == '0':
            return self.desconto
        else:
            tot_sem_desc = self.get_total_sem_desconto()
            v_desconto = tot_sem_desc * (self.desconto / 100)
            return v_desconto

    def get_total_impostos(self):
        return sum(filter(None, [self.vicms, self.vipi]))

    def get_total_com_impostos(self):
        total_com_impostos = self.subtotal + self.get_total_impostos()
        return total_com_impostos

    def format_total_impostos(self):
        return locale.format(u'%.2f', self.get_total_impostos(), 1)

    def format_total_com_imposto(self):
        return locale.format(u'%.2f', self.get_total_com_impostos(), 1)

    def format_desconto(self):
        return '{0}'.format(locale.format(u'%.2f', self.get_valor_desconto(), 1))

    def format_quantidade(self):
        return locale.format(u'%.2f', self.quantidade, 1)

    def format_valor_unit(self):
        return locale.format(u'%.2f', self.valor_unit, 1)

    def format_total(self):
        return locale.format(u'%.2f', self.subtotal, 1)

    def format_vprod(self):
        return locale.format(u'%.2f', self.vprod, 1)

    def format_valor_attr(self, nome_attr):
        valor = getattr(self, nome_attr)
        if valor is not None:
            return locale.format(u'%.2f', valor, 1)


class Compra(models.Model):
    # Fornecedor
    fornecedor = models.ForeignKey(
        'cadastro.Fornecedor', related_name="compra_fornecedor", on_delete=models.CASCADE)
    # Transporte
    mod_frete = models.CharField(
        max_length=1, choices=MOD_FRETE_ESCOLHAS, default='9')
    # Estoque
    local_dest = models.ForeignKey(
        'estoque.LocalEstoque', related_name="compra_local_estoque", default=DEFAULT_LOCAL_ID, on_delete=models.PROTECT)
    movimentar_estoque = models.BooleanField(default=True)
    # Info
    data_emissao = models.DateField(null=True, blank=True)
    valor_total = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                      MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    tipo_desconto = models.CharField(
        max_length=1, choices=TIPOS_DESCONTO_ESCOLHAS, default='0')
    desconto = models.DecimalField(max_digits=15, decimal_places=4, validators=[
                                   MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    despesas = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    frete = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    seguro = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    total_icms = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    total_ipi = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                    MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    cond_pagamento = models.ForeignKey(
        'vendas.CondicaoPagamento', related_name="compra_pagamento", on_delete=models.SET_NULL, null=True, blank=True)
    observacoes = models.CharField(max_length=1055, null=True, blank=True)

    def get_total_sem_imposto(self):
        total_sem_imposto = self.valor_total - self.impostos
        return total_sem_imposto

    def get_total_produtos(self):
        itens = ItensCompra.objects.filter(compra_id=self.id)
        tot = 0
        for it in itens:
            tot += it.vprod
        return tot

    def get_total_produtos_estoque(self):
        itens = self.itens_compra.all()
        tot = 0
        for it in itens:
            if it.produto.controlar_estoque:
                tot += it.vprod
        return tot

    def format_total_produtos(self):
        return locale.format(u'%.2f', self.get_total_produtos(), 1)

    @property
    def impostos(self):
        return (self.total_icms + self.total_ipi)

    @property
    def format_data_emissao(self):
        return '%s' % date(self.data_emissao, "d/m/Y")

    def format_valor_total(self):
        return locale.format(u'%.2f', self.valor_total, 1)

    def format_frete(self):
        return locale.format(u'%.2f', self.frete, 1)

    def format_impostos(self):
        return locale.format(u'%.2f', self.impostos, 1)

    def format_vicms(self):
        return locale.format(u'%.2f', self.total_icms, 1)

    def format_vipi(self):
        return locale.format(u'%.2f', self.total_ipi, 1)

    def format_total_sem_imposto(self):
        return locale.format(u'%.2f', self.get_total_sem_imposto(), 1)

    def format_desconto(self):
        if self.tipo_desconto == '0':
            return locale.format(u'%.2f', self.desconto, 1)
        else:
            itens = ItensCompra.objects.filter(compra_id=self.id)
            tot = 0
            for it in itens:
                tot += it.get_total_sem_desconto()

            v_desconto = tot * (self.desconto / 100)
            return locale.format(u'%.2f', v_desconto, 1)

    def format_seguro(self):
        return locale.format(u'%.2f', self.seguro, 1)

    def format_despesas(self):
        return locale.format(u'%.2f', self.despesas, 1)

    def format_total_sem_desconto(self):
        total_sem_desconto = self.valor_total - self.desconto
        return locale.format(u'%.2f', total_sem_desconto, 1)

    def get_forma_pagamento(self):
        if self.cond_pagamento:
            return self.cond_pagamento.get_forma_display()
        else:
            return ""

    def get_local_dest_id(self):
        if self.local_dest:
            return self.local_dest.id
        else:
            return ""

    def get_child(self):
        try:
            return PedidoCompra.objects.get(id=self.id)
        except PedidoCompra.DoesNotExist:
            return OrcamentoCompra.objects.get(id=self.id)

    def __unicode__(self):
        s = u'Compra nº %s' % (self.id)
        return s

    def __str__(self):
        s = u'Compra nº %s' % (self.id)
        return s


class OrcamentoCompra(Compra):
    data_vencimento = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=1, choices=STATUS_ORCAMENTO_ESCOLHAS, default='0')

    class Meta:
        verbose_name = "Orçamento de Compra"

    @property
    def format_data_vencimento(self):
        return '%s' % date(self.data_vencimento, "d/m/Y")

    @property
    def tipo_compra(self):
        return 'Orçamento'

    def edit_url(self):

compras/models/pagamento.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal

import locale
locale.setlocale(locale.LC_ALL, '')

# Tabela diferente das vendas.


class Pagamento(models.Model):
    compra_id = models.ForeignKey(
        'compras.Compra', related_name="parcela_pagamento", on_delete=models.CASCADE)
    indice_parcela = models.IntegerField()
    vencimento = models.DateField()
    valor_parcela = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                        MinValueValidator(Decimal('0.00'))])

    @property
    def format_valor_parcela(self):
        return locale.format(u'%.2f', self.valor_parcela, 1)

    @property
    def format_vencimento(self):
        return self.vencimento.strftime('%d/%m/%Y')

compras/forms/pagamento.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _
from django.forms import inlineformset_factory

from compras.models import Compra, Pagamento


class PagamentoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PagamentoForm, self).__init__(*args, **kwargs)
        self.fields['valor_parcela'].localize = True

    class Meta:
        model = Pagamento
        fields = ('indice_parcela', 'vencimento', 'valor_parcela',)
        widgets = {
            'indice_parcela': forms.TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'vencimento': forms.DateInput(attrs={'class': 'form-control datepicker'}),
            'valor_parcela': forms.TextInput(attrs={'class': 'form-control decimal-mask'}),
        }
        labels = {
            'indice_parcela': _('Ind. Parcela'),
            'vencimento': _('Vencimento'),
            'valor_parcela': _('Valor'),
        }


PagamentoFormSet = inlineformset_factory(
    Compra, Pagamento, form=PagamentoForm, extra=1, can_delete=True)

templates/compras/orcamento_compra/orcamento_compra_add.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{title_complete}}
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form id="compra_form_add" role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'compras/compra_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'compras/compra_jsblock.html' %} 
  
{% endblock %}

templates/compras/orcamento_compra/orcamento_compra_edit.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{title_complete}}
            </h2>
            <div class="header-btn">
              <a id="gerar_pdf_compra" href="{% url 'compras:gerarpdforcamentocompra' object.id %}" class="btn btn-primary">GERAR PDF</a>
              {% if object.status == '0' %}
              <a id="gerar_pedido_compra" href="{% url 'compras:gerarpedidocompra' object.id %}" class="btn btn-success">GERAR PEDIDO</a>
              <a id="cancelar_orcamento_compra" href="{% url 'compras:cancelarorcamentocompra' object.id %}" class="btn btn-red">CANCELAR</a>
              {% else %}
              <a id="gerar_copia_orcamento_compra" href="{% url 'compras:copiarorcamentocompra' object.id %}" class="btn btn-primary">GERAR CÓPIA DO ORÇAMENTO</a>
              {% endif %}
            </div>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form id="compra_form_edit" role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'compras/compra_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'compras/compra_jsblock.html' %} 
  
{% endblock %}

templates/compras/orcamento_compra/orcamento_compra_list.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    {% include 'base/title_header.html' %}
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              {{title_complete}}
            </h2>
              <div class="header-btn">
                <a href="{{add_url}}" class="btn btn-success"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>                   
                  <th>Status</th>
                  <th>Fornecedor</th>
                  <th>Data de vencimento</th>
                  <th>Total</th>
                  <th>Gerar pedido</th>
                  <th>Cancelar</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_orcamentos%}
               {% for orcamento in all_orcamentos %}
               <tr class="clickable-row" data-href="{% url 'compras:editarorcamentocompraview' orcamento.id %}">
                <td>{{orcamento.id}}</td>
                <td><b>{{orcamento.get_status_display}}</b></td>
                <td>{{orcamento.fornecedor|default_if_none:""}}</td>
                <td>{{orcamento.format_data_vencimento|default_if_none:""}}</td>
                <td>{{orcamento.format_valor_total}}</td>
                {% if orcamento.status == '0' %}
                <td class="green_td" style="text-align:center;padding:0px;height:100%;"><a href="{% url 'compras:gerarpedidocompra' orcamento.id %}" class="prevent-click-row" style="color:green;height:100%;width:100%;display:block;"><i class="material-icons" style="margin-top:8px;">&#xE86C;</i></a></td>
                <td class="red_td" style="text-align:center;padding:0px;height:100%;"><a href="{% url 'compras:cancelarorcamentocompra' orcamento.id %}" class="prevent-click-row" style="color:red;height:100%;width:100%;display:block;"><i class="material-icons" style="margin-top:8px;">&#xE033;</i></a></td>
                {% else %}
                <td></td>
                <td></td>
                {% endif %}
                <td class="lista-remove">
                  <input type="checkbox" name="{{orcamento.id}}" id="remover-entrada-{{orcamento.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{orcamento.id}}"></label>
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

  </div>
</div>

</div>
</section>


{%endblock%}