fiscal/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'fiscal'
urlpatterns = [
    # Nota fiscal saida
    # fiscal/notafiscal/saida/adicionar/
    path(r'notafiscal/saida/adicionar/$',
        views.AdicionarNotaFiscalSaidaView.as_view(), name='addnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/listanotafiscal
    path(r'notafiscal/saida/listanotafiscal/$',
        views.NotaFiscalSaidaListView.as_view(), name='listanotafiscalsaidaview'),
    # fiscal/notafiscal/saida/editar/
    path(r'notafiscal/saida/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalSaidaView.as_view(
    ), name='editarnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/importar/
    path(r'notafiscal/saida/importar/$',
        views.ImportarNotaSaidaView.as_view(), name='importarnotafiscalsaida'),
    # fiscal/notafiscal/saida/gerar/
    path(r'notafiscal/saida/gerar/(?P<pk>[0-9]+)/$',
        views.GerarNotaFiscalSaidaView.as_view(), name='gerarnotafiscalsaida'),

    # Nota fiscal entrada
    # fiscal/notafiscal/entrada/listanotafiscal
    path(r'notafiscal/entrada/listanotafiscal/$',
        views.NotaFiscalEntradaListView.as_view(), name='listanotafiscalentradaview'),
    # fiscal/notafiscal/entrada/editar/
    path(r'notafiscal/entrada/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalEntradaView.as_view(
    ), name='editarnotafiscalentradaview'),
    # fiscal/notafiscal/entrada/importar/
    path(r'notafiscal/entrada/importar/$',
        views.ImportarNotaEntradaView.as_view(), name='importarnotafiscalentrada'),

    # Configuracao NF-e
    path(r'notafiscal/configuracaonotafiscal/$',
        views.ConfiguracaoNotaFiscalView.as_view(), name='configuracaonotafiscal'),

    # Natureza operacao
    # fiscal/naturezaoperacao/adicionar/
    path(r'naturezaoperacao/adicionar/$',
        views.AdicionarNaturezaOperacaoView.as_view(), name='addnaturezaoperacaoview'),
    # fiscal/naturezaoperacao/listanaturezaoperacao
    path(r'naturezaoperacao/listanaturezaoperacao/$',
        views.NaturezaOperacaoListView.as_view(), name='listanaturezaoperacaoview'),
    # fiscal/naturezaoperacao/editar/
    path(r'naturezaoperacao/editar/(?P<pk>[0-9]+)/$', views.EditarNaturezaOperacaoView.as_view(
    ), name='editarnaturezaoperacaoview'),

    # Grupo fiscal
    # fiscal/grupofiscal/adicionar/
    path(r'grupofiscal/adicionar/$',
        views.AdicionarGrupoFiscalView.as_view(), name='addgrupofiscalview'),
    # fiscal/grupofiscal/listagrupofiscalview
    path(r'grupofiscal/listagrupofiscal/$',
        views.GrupoFiscalListView.as_view(), name='listagrupofiscalview'),
    # fiscal/grupofiscal/editar/
    path(r'grupofiscal/editar/(?P<pk>[0-9]+)/$',
        views.EditarGrupoFiscalView.as_view(), name='editargrupofiscalview'),

    # Acoes Nota Fiscal
    # Validar XML nota
    path(r'notafiscal/validar/(?P<pk>[0-9]+)/$',
        views.ValidarNotaView.as_view(), name='validarnotafiscal'),
    # fiscal/notafiscal/emitir/
    path(r'notafiscal/emitir/(?P<pk>[0-9]+)/$',
        views.EmitirNotaView.as_view(), name='emitirnotafiscal'),
    # Clonar nota
    path(r'notafiscal/copiar/(?P<pk>[0-9]+)/$',
        views.GerarCopiaNotaView.as_view(), name='copiarnotafiscal'),
    # Cancelar nota
    path(r'notafiscal/cancelar/(?P<pk>[0-9]+)/$',
        views.CancelarNotaView.as_view(), name='cancelarnotafiscal'),
    # Gerar DANFE
    path(r'notafiscal/gerardanfe/(?P<pk>[0-9]+)/$',
        views.GerarDanfeView.as_view(), name='gerardanfe'),
    # Gerar DANFCE
    path(r'notafiscal/gerardanfce/(?P<pk>[0-9]+)/$',
        views.GerarDanfceView.as_view(), name='gerardanfce'),

    # Comunicacao SEFAZ
    # Consultar cadastro
    path(r'notafiscal/consultarcadastro/$',
        views.ConsultarCadastroView.as_view(), name='consultarcadastro'),
    # Inutilizar notas
    path(r'notafiscal/inutilizarnotas/$',
        views.InutilizarNotasView.as_view(), name='inutilizarnotas'),
    # Consultar nota
    path(r'notafiscal/consultarnota/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    path(r'^notafiscal/consultarnota/(?P<pk>[0-9]+)/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    # Baixar nota
    path(r'notafiscal/baixarnota/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    path(r'^notafiscal/baixarnota/(?P<pk>[0-9]+)/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    # Manifestacao destinatario
    path(r'notafiscal/manifestacaodestinatario/$',
        views.ManifestacaoDestinatarioView.as_view(), name='manifestacaodestinatario'),
]

tcc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('cadastro/', include('cadastro.urls')),
    path('fiscal/', include('fiscal.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
    path('financeiro/', include('financeiro.urls')),
    path('estoque/', include('estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fiscal/models/nota_fiscal.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import RegexValidator, MinValueValidator
from django.template.defaultfilters import date

from decimal import Decimal
import os
import re

from tcc.settings import MEDIA_ROOT, APP_ROOT


IND_PAG_ESCOLHAS = (
    (u'0', u'Pagamento à vista'),
    (u'1', u'Pagamento a prazo'),
    (u'2', u'Outros'),
)

MOD_NFE_ESCOLHAS = (
    (u'55', u'NF-e (55)'),
    (u'65', u'NFC-e (65)'),
)

TP_NFE_ESCOLHAS = (
    (u'0', u'Entrada'),
    (u'1', u'Saída'),
)

IDDEST_ESCOLHAS = (
    (u'1', u'Operação interna'),
    (u'2', u'Operação interestadual'),
    (u'3', u'Operação com exterior'),
)

TP_IMP_ESCOLHAS = (
    (u'0', u'Sem geração de DANFE'),
    (u'1', u'DANFE normal, Retrato'),
    (u'2', u'DANFE normal, Paisagem'),
    (u'4', u'DANFE NFC-e'),
)

TP_EMIS_ESCOLHAS = (
    (u'1', u'Emissão normal'),
    (u'2', u'Emissão em contingência'),
)

TP_AMB_ESCOLHAS = (
    (u'1', 'Produção'),
    (u'2', 'Homologação'),
)

FIN_NFE_ESCOLHAS = (
    (u'1', u'NF-e normal'),
    (u'2', u'NF-e complementar'),
    (u'3', u'NF-e de ajuste'),
    (u'4', u'Devolução de mercadoria'),
)

IND_FINAL_ESCOLHAS = (
    (u'0', u'0 - Não'),
    (u'1', u'1 - Sim'),
)

IND_PRES_ESCOLHAS = (
    (u'0', u'Não se aplica'),
    (u'1', u'Operação presencial'),
    (u'2', u'Operação não presencial, pela Internet'),
    (u'3', u'Operação não presencial, Teleatendimento'),
    (u'4', u'NFC-e em operação com entrega a domicílio'),
    (u'5', u'Operação presencial, fora do estabelecimento'),
    (u'9', u'Operação não presencial, outros.'),
)

VERSOES = (
    ('3.10', 'v3.10'),
)

ORIENTACAO_LOGO_DANFE = (
    (u'H', u'Horizontal'),
    (u'V', u'Vertical'),
)

STATUS_NFE_ESCOLHAS = (
    (u'0', u'Assinada'),
    (u'1', u'Autorizada'),
    (u'2', u'Denegada'),
    (u'3', u'Em Digitação'),
    (u'4', u'Em Processamento na SEFAZ'),
    (u'5', u'Rejeitada'),
    (u'6', u'Validada'),
    (u'7', u'Pendente'),
    (u'8', u'Cancelada'),
    (u'9', u'Importada por XML')
)

ERROS_NFE_TIPOS = (
    (u'0', 'Erro'),
    (u'1', 'Alerta'),
)

RETORNO_SEFAZ_TIPOS = (
    (u'0', u'Erro'),
    (u'1', u'Resultado do processamento'),
    (u'2', u'Rejeição'),
    (u'3', u'Motivo denegação'),
    (u'4', u'Alerta'),
)


def arquivo_proc_path(instance, filename):
    return 'ArquivosXML/ProcNFeUpload/{0}'.format(filename)


class NotaFiscal(models.Model):
    chave = models.CharField(max_length=44)
    versao = models.CharField(max_length=4, choices=VERSOES, default='3.10')
    natop = models.CharField(max_length=60)
    indpag = models.CharField(max_length=1, choices=IND_PAG_ESCOLHAS)
    mod = models.CharField(
        max_length=2, choices=MOD_NFE_ESCOLHAS, default=u'55')
    serie = models.CharField(max_length=3)
    dhemi = models.DateTimeField()
    dhsaient = models.DateTimeField(null=True, blank=True)
    iddest = models.CharField(max_length=1, choices=IDDEST_ESCOLHAS)
    tp_imp = models.CharField(max_length=1, choices=TP_IMP_ESCOLHAS)
    tp_emis = models.CharField(
        max_length=1, choices=TP_EMIS_ESCOLHAS, default=u'1')
    tp_amb = models.CharField(max_length=1, choices=TP_AMB_ESCOLHAS)
    fin_nfe = models.CharField(
        max_length=1, choices=FIN_NFE_ESCOLHAS, default=u'1')
    ind_final = models.CharField(
        max_length=1, choices=IND_FINAL_ESCOLHAS, default=u'0')
    ind_pres = models.CharField(
        max_length=1, choices=IND_PRES_ESCOLHAS, default=u'0')

    inf_ad_fisco = models.CharField(max_length=2000, null=True, blank=True)
    inf_cpl = models.CharField(max_length=5000, null=True, blank=True)

    status_nfe = models.CharField(max_length=1, choices=STATUS_NFE_ESCOLHAS)
    arquivo_proc = models.FileField(
        max_length=2055, upload_to=arquivo_proc_path, null=True, blank=True)
    numero_lote = models.CharField(max_length=16, null=True, blank=True)
    numero_protocolo = models.CharField(max_length=16, null=True, blank=True)
    just_canc = models.CharField(max_length=255, null=True, blank=True)

    @property
    def consumidor(self):
        if self.mod == '65':
            return True
        else:
            return False

    @property
    def contingencia(self):
        if self.tp_emis == '1':
            return False
        else:
            return True

    @property
    def caminho_proc_completo(self):
        if self.arquivo_proc:
            if APP_ROOT in self.arquivo_proc.name:
                return self.arquivo_proc.name
            else:
                return os.path.join(APP_ROOT, self.arquivo_proc.url)
        else:
            return ''

    def format_data_emissao(self):
        return '%s' % date(self.dhemi.date(), "d/m/Y")


class NotaFiscalSaida(NotaFiscal):
    tpnf = models.CharField(
        max_length=1, choices=TP_NFE_ESCOLHAS, default=u'1')
    n_nf_saida = models.CharField(max_length=9, validators=[
                                  RegexValidator(r'^\d{1,10}$')], unique=True)
    venda = models.ForeignKey('vendas.PedidoVenda', related_name="venda_nfe",
                              on_delete=models.SET_NULL, null=True, blank=True)
    emit_saida = models.ForeignKey(
        'cadastro.Empresa', related_name="emit_nfe_saida", on_delete=models.SET_NULL, null=True, blank=True)
    dest_saida = models.ForeignKey(
        'cadastro.Cliente', related_name="dest_nfe_saida", on_delete=models.SET_NULL, null=True, blank=True)

    # Cobranca Fatura(NF-e)
    n_fat = models.CharField(max_length=60, null=True, blank=True, unique=True)
    v_orig = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    v_desc = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    v_liq = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    grupo_cobr = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Nota Fiscal"
        permissions = (
            ("emitir_notafiscal", "Pode emitir notas fiscais"),
            ("cancelar_notafiscal", "Pode cancelar notas fiscais"),
            ("gerar_danfe", "Pode gerar DANFE/DANFCE"),
            ("consultar_cadastro", "Pode consultar cadastro no SEFAZ"),
            ("inutilizar_notafiscal", "Pode inutilizar notas fiscais"),
            ("consultar_notafiscal", "Pode consultar notas fiscais"),
            ("baixar_notafiscal", "Pode baixar notas fiscais"),
            ("manifestacao_destinatario", "Pode efetuar manifestação do destinatário"),
        )

    @property
    def estado(self):
        if self.emit_saida:
            if self.emit_saida.endereco_padrao:
                return self.emit_saida.endereco_padrao.uf
        return ''

    def get_emit_cmun(self):
        if self.emit_saida:
            if self.emit_saida.endereco_padrao:
                return self.emit_saida.endereco_padrao.cmun
        return ''

    def __unicode__(self):
        s = u'Série %s,  Nº %s, Chave %s' % (
            self.serie, self.n_nf_saida, self.chave)
        return s

    def __str__(self):
        s = u'Série %s,  Nº %s, Chave %s' % (
            self.serie, self.n_nf_saida, self.chave)
        return s


class NotaFiscalEntrada(NotaFiscal):
    n_nf_entrada = models.CharField(max_length=9, validators=[
                                    RegexValidator(r'^\d{1,10}$')])
    compra = models.ForeignKey('compras.PedidoCompra', related_name="compra_nfe",
                               on_delete=models.SET_NULL, null=True, blank=True)
    emit_entrada = models.ForeignKey(
        'cadastro.Fornecedor', related_name="emit_nfe_entrada", on_delete=models.SET_NULL, null=True, blank=True)
    dest_entrada = models.ForeignKey(
        'cadastro.Empresa', related_name="dest_nfe_entrada", on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "Nota Fiscal de Fornecedor"

    @property
    def estado(self):
        if self.emit_entrada:
            if self.emit_entrada.endereco_padrao:
                return self.emit_entrada.endereco_padrao.uf
        return ''

    def __unicode__(self):
        s = u'Série %s,  Nº %s, Chave %s' % (
            self.serie, self.n_nf_entrada, self.chave)
        return s

    def __str__(self):
        s = u'Série %s,  Nº %s, Chave %s' % (
            self.serie, self.n_nf_entrada, self.chave)
        return s


class AutXML(models.Model):
    nfe = models.ForeignKey('fiscal.NotaFiscalSaida',
                            related_name="aut_xml", on_delete=models.CASCADE)
    cpf_cnpj = models.CharField(max_length=32, null=True, blank=True)

    def get_cpf_cnpj_apenas_digitos(self):
        return re.sub('[./-]', '', self.cpf_cnpj)


class ConfiguracaoNotaFiscal(models.Model):
    arquivo_certificado_a1 = models.FileField(
        upload_to='arquivos/certificado/', null=True, blank=True)
    senha_certificado = models.CharField(max_length=255, null=True, blank=True)
    serie_atual = models.CharField(max_length=3, default='101')
    ambiente = models.CharField(
        max_length=1, choices=TP_AMB_ESCOLHAS, default=u'2')
    imp_danfe = models.CharField(
        max_length=1, choices=TP_IMP_ESCOLHAS, default=u'1')

    inserir_logo_danfe = models.BooleanField(default=True)
    orientacao_logo_danfe = models.CharField(
        max_length=1, choices=ORIENTACAO_LOGO_DANFE, default=u'H')

    csc = models.CharField(max_length=64, null=True, blank=True)
    cidtoken = models.CharField(max_length=8, null=True, blank=True)

    class Meta:
        default_permissions = ()
        verbose_name = "Configuração NF-e"
        permissions = (
            ("configurar_nfe", "Pode modificar configuração de NF-e"),
        )

    @property
    def leiaute_logo_vertical(self):
        if self.orientacao_logo_danfe == 'H':

fiscal/views/natureza_operacao.py
# -*- coding: utf-8 -*-

from django.urls import reverse_lazy

from base.custom_views import CustomCreateView, CustomListView, CustomUpdateView

from fiscal.forms import NaturezaOperacaoForm
from fiscal.models import NaturezaOperacao


class AdicionarNaturezaOperacaoView(CustomCreateView):
    form_class = NaturezaOperacaoForm
    template_name = "fiscal/natureza_operacao/natureza_operacao_add.html"
    success_url = reverse_lazy('fiscal:listanaturezaoperacaoview')
    success_message = "Natureza da operação <b>%(cfop)s </b>adicionada com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarNaturezaOperacaoView,
                        self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR NATUREZA DA OPERAÇÃO'
        context['return_url'] = reverse_lazy(
            'fiscal:listanaturezaoperacaoview')
        return context


class NaturezaOperacaoListView(CustomListView):
    template_name = 'fiscal/natureza_operacao/natureza_operacao_list.html'
    model = NaturezaOperacao
    context_object_name = 'all_natops'
    success_url = reverse_lazy('fiscal:listanaturezaoperacaoview')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(NaturezaOperacaoListView,
                        self).get_context_data(**kwargs)
        context['title_complete'] = 'NATUREZAS DA OPERAÇÃO CADASTRADAS'
        context['add_url'] = reverse_lazy('fiscal:addnaturezaoperacaoview')
        return context


class EditarNaturezaOperacaoView(CustomUpdateView):
    form_class = NaturezaOperacaoForm
    model = NaturezaOperacao
    template_name = "fiscal/natureza_operacao/natureza_operacao_edit.html"
    success_url = reverse_lazy('fiscal:listanaturezaoperacaoview')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarNaturezaOperacaoView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'fiscal:listanaturezaoperacaoview')
        return context

templates/fiscal/nota_fiscal/modal_importar_nota.html
<!-- Modal escolher arquivo xml para importacao de nfes -->
<div class="modal fade importar_nota_modal">
  <div class="modal-dialog modal-lg">
    <form id="form_importar_nota" action="{{importar_nota_url}}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">IMPORTAÇÃO DE NOTA FISCAL {% if entrada %} DE FORNECEDOR{% endif %}</h4>
        </div>
        <div class="modal-body">
          <div class="container-fluid">

            <!-- SELECIONAR ARQUIVO XML -->
            <div class="row">
              <h4 style="border-bottom: 1px solid #afabab;">Selecione o arquivo da Nota Fiscal</h4>
            </div>
            
            <div class="row">

              <div class="col-sm-12">
                <div class="form-group">
                  <div class="form-line">
                    <label>Arquivo XML</label>
                    <input class="form-control" id="id_arquivo_xml_nfe" name="arquivo_xml" type="file" accept="text/xml" required/>
                  </div>
                </div>
              </div>

              {% if saida %}
              <input class="hidden" name="fornecedor" type="checkbox"/>
              {% elif entrada %}
              <input class="hidden" name="fornecedor" type="checkbox" checked="true"/>
              {% endif %}

            </div>
            <!-- #SELECIONAR ARQUIVO XML -->

          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">FECHAR</button>
          <button type="submit" class="btn btn-primary" id="importar_nota_btn">IMPORTAR</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- #-->

templates/fiscal/nota_fiscal/nota_fiscal_edit.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">
          {% include 'base/msg_error.html' %}
          <b>{% include 'base/msg_sucesso.html' %}</b>
          <!--Header-->
          <div class="header" style="overflow:visible;">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a> {{title_complete}}
            </h2>
            <div class="header-btn">
              {% if saida %}
              <div class="dropdown" style="display: inline-block;float:right;">
                <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">Ações
                <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                  <li><a href="{% url 'fiscal:validarnotafiscal' object.id %}">Validar XML</a></li>
                  <li><a href="{% url 'fiscal:emitirnotafiscal' object.id %}">Emitir Nota</a></li>
                  <li><a href="{% url 'fiscal:consultarnota' object.id %}">Consultar Nota</a></li>
                  <li><a href="{% url 'fiscal:baixarnota' object.id %}">Baixar Nota</a></li>
                  <li><a href="{% url 'fiscal:cancelarnotafiscal' object.id %}">Cancelar Nota</a></li>
                  <li><a href="{% url 'fiscal:copiarnotafiscal' object.id %}">Clonar Nota</a></li>
                  {% if object.mod == '55' %}
                  <li><a href="{% url 'fiscal:gerardanfe' object.id %}">Gerar DANFE</a></li>
                  {% elif object.mod == '65' %}
                  <li><a href="{% url 'fiscal:gerardanfce' object.id %}">Gerar DANFCE</a></li>
                  {% endif %}
                </ul>
              </div>
              {% endif %}
            </div>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% include 'fiscal/nota_fiscal/nota_fiscal_form.html' %}

          </form>

          {% if saida %}
          {% include 'fiscal/nota_fiscal/modal_detalhe_produto_venda.html' %}
          {% elif entrada %}
          {% include 'fiscal/nota_fiscal/modal_detalhe_produto_compra.html' %}
          {% endif %}

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'fiscal/nota_fiscal/nota_fiscal_jsblock.html' %}
  
{% endblock %}

templates/fiscal/nota_fiscal/nota_fiscal_list.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">

    {% include 'base/title_header.html' %}
    
    {% include 'base/msg_sucesso.html' %}
    {% include 'base/msg_error.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              {{title_complete}}
            </h2>
            <div class="header-btn">
              {% if saida %}
              <a href="{{add_url}}" class="btn btn-success"><i class="material-icons">&#xE148;</i><span> NOVA NOTA</span></a>
              {% endif %}
              <a id="importar_nota" href="javascript:void(0);" class="btn btn-primary"><i class="material-icons">&#xE884;</i><span>IMPORTAR NOTA</span></a>
              <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
            </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>
                  <th>Mod.</th>
                  <th>Série/Número</th>
                  <th>Data de emissão</th>
                  {% if saida %}
                  <th>Cliente</th>
                  {% elif entrada %}
                  <th>Fornecedor</th>
                  {% endif %}
                  <th>Status</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_notas%}
               {% for nota in all_notas %}
               {% if saida %}
               <tr class="clickable-row" data-href="{% url 'fiscal:editarnotafiscalsaidaview' nota.id %}">
               {% elif entrada %}
               <tr class="clickable-row" data-href="{% url 'fiscal:editarnotafiscalentradaview' nota.id %}">
               {% endif %}
                <td>{{nota.id}}</td>
                <td>{{nota.get_mod_display}}</td>
                <td>{{nota.serie}}/{% if saida %}{{nota.n_nf_saida}}{% elif entrada %}{{nota.n_nf_entrada}}{% endif %}</td>
                <td>{{nota.format_data_emissao|default_if_none:""}}</td>
                <td>{% if saida %}{{nota.dest_saida}}{% elif entrada %}{{nota.emit_entrada}}{% endif %}</td>
                <td>{{nota.get_status_nfe_display}}</td>
                <td class="lista-remove">
                  <input type="checkbox" name="{{nota.id}}" id="remover-entrada-{{nota.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{nota.id}}"></label>
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

    {% include 'fiscal/nota_fiscal/modal_importar_nota.html' %}
  </div>
</div>

</div>
</section>


{%endblock%}

{% block js %}
  {% include 'base/load_jqueryui.html' %}

  {% include 'base/tooltip_js.html' %}
    
   <script type="text/javascript">
    $('body').on('click', '#importar_nota', function(){
      $('.importar_nota_modal').modal('show');
    });

    $('form[id=form_importar_nota]').on('submit', function(){
        $('.page-loader-wrapper').show();
        {% if entrada %}
        $('.loader .loader-message').text('Importando nota fiscal do fornecedor, aguarde...');
        {% elif saida %}
        $('.loader .loader-message').text('Importando nota fiscal, aguarde...');
        {% endif %}
    });
  </script>
  
{% endblock %}